### ISSUE TITLE
fast_page and graphql-ruby

### ISSUE THREAD

**Issue by sasharevzin** [planetscale/fast_page#10]
I'm trying to use fast_page with [connections](https://graphql-ruby.org/pagination/using_connections).
Is there a way to implement fast_page with graphql-ruby?

**Comment by mscoutermarsh** [comment]
I believe `graphql-ruby` connections use cursor pagination rather than offset/limit.

If that's true, then `fast_page` would not benefit since it only improves performance for offset/limit pagination.

**Comment by sasharevzin** [comment]
It does implement cursor, but looking at [connection implementation](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/pagination/active_record_relation_connection.rb) I found some offset/limit manipulations.
I could [implement the custom](https://graphql-ruby.org/pagination/custom_connections)class it seems to be working. It runs two queries and works as expected
```ruby
module Types
  module Connections
    class FastPageConnection < GraphQL::Pagination::ActiveRecordRelationConnection # rubocop:disable GraphQL/ObjectDescription
      def limited_nodes
        super.fast_page
      end
    end
  end
end
```

**Comment by mscoutermarsh** [comment]
Nice! Please share how it goes. If you have good results, would be useful to document.

**Comment by sasharevzin** [comment]
I'll update

**Comment by sasharevzin** [comment]
It works amazingly fast!
